package com.sanparks.scanDB;

public enum E_ENTRY_REASON {
	ENTRY_REASON_TOURISM,
	ENTRY_REASON_DAY_VISITOR,
	ENTRY_REASON_STAFF,
	ENTRY_REASON_DELIVERIES,
	ENTRY_REASON_RESEARCH,
	ENTRY_REASON_BUSINESS
}
